### ISSUE TITLE
Buckets are not consumed

### ISSUE THREAD

**Issue by Nboopsie** [Darkhax-Minecraft/Resource-Hogs#15]
When a bucket of mud is used on a pig, an empty bucket returns to the hand. It turns duplication of buckets
Tested only on SF4

**Comment by Mysteriez974** [comment]
Also noticed this.
Exact steps to reproduce :

- Craft any Bucket of Mud, using one dirt, a resource, and a bucket of water. Note that only the water is consumed, and the recipe gives you back one empty bucket.
- Feed the Bucket of Mud to a pig. This gives you a second empty bucket.
&nbsp;

Suggestions to correct : 
- Either make the crafting recipe consume the bucket entirely (which I believe from searching around a little would involve extending ShapelessOreRecipe, although I could be wrong about that);
- Or simply change line 75 in ItemMudBucket so it sets held item to ItemStack.EMPTY.
&nbsp;

My preference would be the second one, simply because right now the recipe works with any bucket of water including mod items, and it would be more complicated to store which bucket was used to create the item in order to return it once the MudBucket is used. Unless you want to restrict it to vanilla buckets, which would involve yet another headache.

**Comment by Darkhax** [comment]
Thanks for reporting the issue. The fix by cr998 has now been merged in.
